server:
  port : 8089


spring:
  datasource:
    username: root
#    password: rootadmin
    password: 12345678
    url: jdbc:mysql://localhost:3306/Fly?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.bean


#logging:
#  level:
#    com:
#      example:
#        mapper: debug